name: food_label_ai
description: "An AI-powered food label analyzer using Google Gemini API."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Image Picking - UPDATED VERSION
  image_picker: ^1.1.0

  # HTTP Requests - UPDATED VERSION
  http: ^1.2.0

  # Environment Variables - UPDATED VERSION
  flutter_dotenv: ^5.2.0

  # Material Design
  cupertino_icons: ^1.0.2
  firebase_core: ^4.9.0
  firebase_auth: ^6.5.1
  cloud_firestore: ^6.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Lints - UPDATED VERSION
  flutter_lints: ^4.0.0

flutter:
  # To make sure your app uses the latest Material 3 design features
  uses-material-design: true
  
  # Crucial for the dotenv package to find your API key
  assets:
    - .env