// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZWT2cHlPfbla5RxS4p14dNPUvcyUgJ8g',
    appId: '1:139205123544:web:db71690ca895215492e6ad',
    messagingSenderId: '139205123544',
    projectId: 'food-label-ai-d5970',
    authDomain: 'food-label-ai-d5970.firebaseapp.com',
    storageBucket: 'food-label-ai-d5970.firebasestorage.app',
    measurementId: 'G-G5XE91DVBN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMMkGFvGEp330URwj0CraIqWY1NBsjR9A',
    appId: '1:139205123544:android:b35234c5ad023b1292e6ad',
    messagingSenderId: '139205123544',
    projectId: 'food-label-ai-d5970',
    storageBucket: 'food-label-ai-d5970.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByokCAr26QVV41WEijOp8XR9obcaNxJPQ',
    appId: '1:139205123544:ios:523a0340ebdb62f792e6ad',
    messagingSenderId: '139205123544',
    projectId: 'food-label-ai-d5970',
    storageBucket: 'food-label-ai-d5970.firebasestorage.app',
    iosBundleId: 'com.rohith.foodlabelai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByokCAr26QVV41WEijOp8XR9obcaNxJPQ',
    appId: '1:139205123544:ios:09667d9cbb175d8892e6ad',
    messagingSenderId: '139205123544',
    projectId: 'food-label-ai-d5970',
    storageBucket: 'food-label-ai-d5970.firebasestorage.app',
    iosBundleId: 'com.example.foodLabelAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZWT2cHlPfbla5RxS4p14dNPUvcyUgJ8g',
    appId: '1:139205123544:web:f4ab768d39b50df292e6ad',
    messagingSenderId: '139205123544',
    projectId: 'food-label-ai-d5970',
    authDomain: 'food-label-ai-d5970.firebaseapp.com',
    storageBucket: 'food-label-ai-d5970.firebasestorage.app',
    measurementId: 'G-1R3S5MT1KV',
  );

}